EE_REGION = ntscu

include ${CURDIR}/Makefile.defs

EE_LIBS = -lrac2ntscu
EE_DEFS = -DGC_NTSCU -DRAC2_NTSCU -DNTSCU
PNACH_NAME = SCUS-97268_38996035

include ${CURDIR}/../Makefile.pref
include ${CURDIR}/../Makefile.eeglobal
